Gro/ViewModels/Pages/AppPages/Agreement/AgreementPageViewModel.cs
using System.Collections.Generic;
using System.Linq;
using Gro.Core.ContentTypes.Pages.AppPages;
using Gro.Core.DataModels.AgreementDtos;

namespace Gro.ViewModels.Pages.AppPages.Agreement
{
    public class AgreementPageViewModel : PageViewModel<AgreementPage>
    {
        public AgreementPageViewModel(AgreementPage currentPage) : base(currentPage)
        { }

        public IEnumerable<IGrouping<int, Core.DataModels.AgreementDtos.Agreement>> ListAgreementsByYears { get; set; }

        public IEnumerable<IGrouping<int, SeedAssurance>> ListSeedAgreementsByYears { get; set; }

        public List<DryAgreement> ListDryAgreements { get; set; }

        public IEnumerable<IGrouping<int, Core.DataModels.AgreementDtos.Agreement>> ListFarmingAgreements { get; set; }
    }

    public class AgreementAnalyzeViewModel
    {
        // list ordered analysis.ProvNr
        public IEnumerable<string> AnalysisProvNrs { get; set; }

        public Dictionary<string, List<string>> DictResultByAnalyskod { get; set; }

        public string AgreementNumber { get; set; }
    }
}

Gro/ViewModels/Pages/AppPages/DeliveryNote/DeliveryNotePageViewModel.cs
using System.Collections.Generic;
using Gro.Business.Paging;
using Gro.Core.ContentTypes.Pages.AppPages;
using Gro.Core.DataModels.DeliveryNoteDtos;

namespace Gro.ViewModels.Pages.AppPages.DeliveryNote
{
    public class DeliveryNotePageViewModel : PageViewModel<DeliveryNotePage>
    {
        public DeliveryNotePageViewModel(DeliveryNotePage currentPage) : base(currentPage)
        {
        }

        public IEnumerable<FoljesedelResponse> ListDeliveries { get; set; }
        public Pager Pager { get; set; }
    }
}

Gro/ViewModels/Pages/AppPages/DryingAgreement/DryingAgreementViewModel.cs
using Gro.Core.ContentTypes.Pages.AppPages;
using Gro.Core.DataModels.PurchasingAgreements;

namespace Gro.ViewModels.Pages.AppPages.DryingAgreement
{
    public class DryingAgreementViewModel : PageViewModel<DryingAgreementPage>
    {
        public DryingAgreementViewModel(DryingAgreementPage currentPage) : base(currentPage)
        {
            Agreement = new Core.DataModels.PurchasingAgreements.DryingAgreement();
            Customer = new Customer();
        }
        
        public Core.DataModels.PurchasingAgreements.DryingAgreement Agreement { get; set; }
        public Customer Customer { get; set; }

    }
}

Gro/ViewModels/Pages/AppPages/Grobarhet/GrobarhetPageViewModel.cs
using Gro.Core.ContentTypes.Pages.AppPages;
using Gro.Core.DataModels.GrobarhetDtos;

namespace Gro.ViewModels.Pages.AppPages.Grobarhet
{
    public class GrobarhetPageViewModel : PageViewModel<GrobarhetPage>
    {
        public GrobarhetPageViewModel(GrobarhetPage page) : base(page)
        {
        }

        public GrobarhetResponse[] SearchItems { get; set; }
    }
}

Gro/ViewModels/Pages/AppPages/WeighIn/CustomerSelectViewModel.cs
namespace Gro.ViewModels.Pages.AppPages.WeighIn
{
    public class CustomerSelectViewModel
    {
        public string CustomerName { get; set; }
        public string CustomerNumber { get; set; }
    }
}

Gro/Controllers/NavigationController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using EPiServer;
using EPiServer.Core;
using Gro.Business.Services.News;
using Gro.Core.ContentTypes.Pages;
using Gro.Core.ContentTypes.Pages.BasePages;
using Gro.Core.ContentTypes.Pages.StartPages;
using Gro.Core.ContentTypes.Utils;
using Gro.ViewModels.Navigation;
using System;

namespace Gro.Controllers
{
    public class NavigationController : Controller
    {
        private readonly IGroContentDataService _groContentDataService;
        private readonly IContentRepository _contentRepository;

        public NavigationController(IGroContentDataService groContentDataService, IContentRepository contentRepository)
        {
            _groContentDataService = groContentDataService;
            _contentRepository = contentRepository;
        }

        public ActionResult GetTopNav(SitePageBase page)
        {
            //var listServiceStartPages = _groContentDataService.GetChildrenByVisitor<ServiceStartPage>(ContentReference.StartPage, true);
            var startPage = _contentRepository.Get<StartPage>(ContentReference.StartPage);

            var listServiceStartPages = _groContentDataService.GetChildrenForVisitor<ServiceStartPage>(startPage,
                HttpContext);
            var model = new TopNavigationModel();

            var serviceStartPages = listServiceStartPages as ServiceStartPage[] ?? listServiceStartPages.ToArray();
            if (serviceStartPages.Any())
            {
                model.ListServiceStartPageItems.AddRange(serviceStartPages.Select(item => new NavigationItemModel
                {
                    ContentLink = item.ContentLink,
                    Text = item.Name,
                    CssClass = GetNavCssClassForService(item)
                }));
            }

            // get service name
            var topLevelServiceStartPage = page as ServiceStartPage ?? _groContentDataService.FindAncestor<ServiceStartPage>(page);
            var startPageRef = topLevelServiceStartPage?.ContentLink ?? ContentReference.EmptyReference;
            var startpageText = topLevelServiceStartPage?.Name ?? string.Empty;

            if (string.IsNullOrEmpty(startpageText))
            {
                var topLevelStartPage = page as StartPage ?? _groContentDataService.FindAncestor<StartPage>(page);
                if (topLevelStartPage != null && !ContentReference.IsNullOrEmpty(topLevelStartPage.SettingsPage))
                {
                    var settingPage = _contentRepository.Get<PageData>(topLevelStartPage.SettingsPage);
                    startpageText = (settingPage as SettingsPage)?.SelectServiceText ?? string.Empty;
                    startPageRef = topLevelStartPage.ContentLink;
                }
            }
            model.StartPageText = startpageText;
            model.StartpageReference = startPageRef;

            return PartialView("Navigations/_TopNavigation", model);
        }

        //private string GetNavCssClassForService(ServiceStartPage serviceStartPage) => serviceStartPage.GetServiceTypeName().ToLower();
        private static string GetNavCssClassForService(ServiceStartPage serviceStartPage)
        {
            if (serviceStartPage is OdlingStartPage)
            {
                return "odling";
            }
            if (serviceStartPage is SpannmalStartPage)
            {
                return "spannmal";
            }
            if (serviceStartPage is EkonomiStartPage)
            {
                return "ekonomi";
            }
            if (serviceStartPage is EkonomiIframeStartPage)
            {
                return "ekonomi";
            }
            if (serviceStartPage is FoderStartPage)
            {
                return "foder";
            }
            if (serviceStartPage is MaskinStartPage)
            {
                return "maskiner";
            }
            return string.Empty;
        }

        public ActionResult GetSubNav(SitePageBase page)
        {
            var startPage = (page as ServiceStartPage) ?? _groContentDataService.FindAncestor<ServiceStartPage>(page);
            var directSubNavigation = (PageData)_groContentDataService.FindAncestor<FolderPage>(page) ?? page;
            var navigationItems = startPage == null
                ? new NavigationItemModel[0]
                : _groContentDataService
                    .GetChildrenForVisitor<PageData>(startPage, HttpContext)
                    .Select(startPageChild => new NavigationItemModel
                    {
                        ContentLink = startPageChild.ContentLink,
                        Text = startPageChild.Name,
                        IsActive = directSubNavigation.ContentGuid == startPageChild.ContentGuid,
                        Children = _groContentDataService
                            .GetChildrenForVisitor<SitePageBase>(startPageChild, HttpContext)
                            .Select(c => new NavigationItemModel
                            {
                                Text = c.Name,
                                ContentLink = c.ContentLink,
                                //IsActive = c.ContentGuid == page.ContentGuid,
                                IsActive = IsSelfOrDirectChild(c, page),
                                Children = _groContentDataService.GetChildrenForVisitor<SitePageBase>(c, HttpContext)
                                    .Select(subChild => new NavigationItemModel
                                    {
                                        Text = subChild.Name,
                                        ContentLink = subChild.ContentLink,
                                        IsActive = IsSelfOrDirectChild(subChild, page),
                                    })
                                    .ToArray()
                            })
                            .ToArray()
                    })
                    .ToArray();

            return PartialView("Navigations/_SubNavigation", navigationItems);
        }

        #region Right navigation model

        public ActionResult GetRightNav(SitePageBase page, int minLevel = 3, Type[] pageTypes = null)
        {
            var rightNavModel = GetRightNavModel(page, minLevel, pageTypes);
            return PartialView("_RightNavigation", rightNavModel);
        }

        private RightNavigationModel GetRightNavModel(PageData currentPage, int minLevel, Type[] pageTypes)
        {
            var model = new RightNavigationModel(currentPage is NonServicePageBase)
            {
                ListNavigationItems = GetRightNavListItems(currentPage, minLevel, pageTypes).ToList()
            };
            var nonServicePage = currentPage as NonServicePageBase;
            if (nonServicePage != null)
            {
                model.Header = GetRightNavHeader(nonServicePage);
            }
            return model;
        }

        private static string GetRightNavHeader(NonServicePageBase currentPage)
        {
            if (!string.IsNullOrEmpty(currentPage.RightNavigationHeader))
            {
                return currentPage.RightNavigationHeader;
            }

            var parent = currentPage.ParentLink.Get<PageData>();
            var parentWithRightNavHeader = parent as NonServicePageFolder;
            return parentWithRightNavHeader != null ? parentWithRightNavHeader.RightNavigationHeader : string.Empty;
        }

        private IEnumerable<NavigationItemModel> GetRightNavListItems(PageData currentPage, int minLevel, Type[] pageTypes)
        {
            var pageLevel = currentPage.GetLevel();
            var result = new List<NavigationItemModel>();
            if (pageLevel < minLevel) return result;

            var childrenOfCurrPage = _groContentDataService.GetChildrenForVisitor<SitePageBase>(currentPage, HttpContext);

            IEnumerable<SitePageBase> listSiblingsAtRootLevel;

            if (childrenOfCurrPage.Any() || pageLevel <= 4)
            {
                //This page will be the one of main nav item together with its siblings.
                listSiblingsAtRootLevel = _groContentDataService.GetSiblingsForVisitor<SitePageBase>(currentPage, HttpContext);
            }
            else
            {
                // this page is the leaf, go up ,find its parent
                var parentPage = _contentRepository.Get<PageData>(currentPage.ParentLink);
                listSiblingsAtRootLevel = _groContentDataService.GetSiblingsForVisitor<SitePageBase>(parentPage ?? currentPage, HttpContext);
            }

            if (pageTypes != null)
            {
                listSiblingsAtRootLevel = listSiblingsAtRootLevel
                    .Where(page => pageTypes.Any(type => type.IsInstanceOfType(page)));
            }

            result.AddRange(listSiblingsAtRootLevel.Select(page => new NavigationItemModel
            {
                ContentLink = page.ContentLink,
                IsActive = page.ContentGuid == currentPage.ContentGuid,
                Text = page.Name,
                Children = _groContentDataService
                    .GetChildrenForVisitor<SitePageBase>(page, HttpContext)
                    .Select(x => CreateNavItem(x, currentPage))
            }));

            return result;
        }

        private static NavigationItemModel CreateNavItem(IContent page, PageData topLevelPage) => new NavigationItemModel
        {
            ContentLink = page.ContentLink,
            IsActive = IsSelfOrDirectChild(page, topLevelPage),
            Text = page.Name
        };

        private static bool IsSelfOrDirectChild(IContent page, PageData targetPage)
            => page.ContentGuid.Equals(targetPage.ContentGuid) || page.ContentLink.Equals(targetPage.ParentLink);

        #endregion
    }
}

Gro/Controllers/Pages/AppPages/AgreementPageController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Web.SessionState;
using EPiServer.Framework.DataAnnotations;
using Gro.Business.Services.Users;
using Gro.Core.ContentTypes.Pages.AppPages;
using Gro.Core.DataModels.AgreementDtos;
using Gro.Core.Interfaces;
using Gro.Infrastructure.Data;
using Gro.ViewModels.Pages.AppPages.Agreement;
using Gro.Helpers;

namespace Gro.Controllers.Pages.AppPages
{
    [SessionState(SessionStateBehavior.Disabled)]
    [TemplateDescriptor(Inherited = true)]
    public class AgreementPageController : SiteControllerBase<AgreementPage>
    {
        private readonly IAgreementRepository _agreementRepository;

        public AgreementPageController(
            IAgreementRepository agreementRepository,
            IUserManagementService usersManagementService,
            TicketProvider ticketProvider,
            IUserManagementService userManager) : base(userManager)
        {
            _agreementRepository = agreementRepository;
        }

        public ActionResult Index(AgreementPage currentPage)
        {
            var supplier = UserManager.GetActiveCustomer(HttpContext);
            if (string.IsNullOrWhiteSpace(supplier?.CustomerNo))
            {
                return View("Index", new AgreementPageViewModel(currentPage)
                {
                    ListAgreementsByYears = new Agreement[0].GroupBy(a => 0),
                    ListSeedAgreementsByYears = new SeedAssurance[0].GroupBy(a => 0),
                    ListFarmingAgreements = new Agreement[0].GroupBy(a => 0),
                    ListDryAgreements = new List<DryAgreement>()
                });
            }

            var model = new AgreementPageViewModel(currentPage)
            {
                ListAgreementsByYears = _agreementRepository.GetAgreementsListByYears(supplier.CustomerNo),
                ListSeedAgreementsByYears = _agreementRepository.GetSeedAgreementsByYears(supplier.CustomerNo),
                ListFarmingAgreements = _agreementRepository.GetFarmingAgreementsByYears(supplier.CustomerNo),
                ListDryAgreements = _agreementRepository.GetDryAgreements(supplier.CustomerNo)
            };

            return View("Index", model);
        }


        [Route("api/agreement/price-hedging/{agreementNumber}")]
        public async Task<ActionResult> GetPriceHedging(string agreementNumber)
        {
            int agreementN;
            if (!int.TryParse(agreementNumber, out agreementN)) return new HttpStatusCodeResult(400);

            var supplier = UserManager.GetActiveCustomer(HttpContext);
            if (string.IsNullOrWhiteSpace(supplier.CustomerNo)) return HttpNotFound();

            var listPriceHedgings = await _agreementRepository.GetPriceHedgingListAsync(supplier.CustomerNo, agreementNumber);
            return PartialView("Dialogs/PriceHedgingBody", listPriceHedgings);
        }

        [Route("api/agreement/farmsample/{agreementNumber}")]
        public async Task<ActionResult> GetFarmSamples(string agreementNumber)
        {
            if (string.IsNullOrWhiteSpace(agreementNumber)) return new HttpStatusCodeResult(400);

            var supplier = UserManager.GetActiveCustomer(HttpContext);
            if (string.IsNullOrWhiteSpace(supplier.CustomerNo)) return HttpNotFound();

            var listPriceHedgings = await _agreementRepository.GetFarmSamplesListAsync(supplier.CustomerNo, agreementNumber);
            var groupOfAnalysis = listPriceHedgings
                .Select(x => new FarmSample { Analyskod = x.Analyskod, Resultat = x.Resultat, ProvNr = x.ProvNr })
                .Distinct()
                .ToList();

            // list all ProvNr
            var listProvNrs = groupOfAnalysis.Select(x => x.ProvNr).Distinct().OrderBy(x => x);

            var listItemByKodAndProvNr = groupOfAnalysis.GroupBy(x => new { x.Analyskod, x.ProvNr })
                .Select(y => new FarmSample
                {
                    Analyskod = y.Key.Analyskod,
                    ProvNr = y.Key.ProvNr,
                    Resultat = y.Select(a => a.Resultat).FirstOrDefault()
                }).OrderBy(x => x.Analyskod).ThenBy(x => x.ProvNr).ToList();

            var dictResultByAnalyskod = new Dictionary<string, List<string>>();
            foreach (var item in listItemByKodAndProvNr)
            {
                dictResultByAnalyskod.AddToDictionary(item.Analyskod, item.Resultat);
            }

            var viewModel = new AgreementAnalyzeViewModel
            {
                AgreementNumber = agreementNumber,
                AnalysisProvNrs = listProvNrs,
                DictResultByAnalyskod = dictResultByAnalyskod
            };
            return PartialView("Dialogs/AnalyzeBody", viewModel);
        }
    }
}

Gro/Views/AppPages/DeliveryAssurancePage/DeliveryAssuranceConfirmation.cshtml
@using Gro.Core.ContentTypes.Utils
@model Gro.ViewModels.Pages.AppPages.DeliveryAssurance.DeliveryAssuranceOverviewViewModel

<!-- START MAIN CONTENT -->
<section class="lm__contents">
    <div class="wrapper">
        <div class="layout  layout--large">
            <div class="layout__item u-1/1 u-2/3-tablet">
                <div class="lm__main-content">
                    <div class="lm__content-detail">
                        <div class="u-1/1 lm__float-left-element lm__row-margin">
                            <div class="lm__float-left-element lm__control-label">
                                <h3 class="no-margin">@ViewBag.Message</h3>
                            </div>
                        </div>

                        @if (ViewBag.WHSubType != null)
                        {
                            <p class="content-summary">@ViewBag.WHSubType</p>
                        }
                    </div>
                    <div class="lm__block lm__mina-avtal">
                        <div class="lm__block ">
                            <div class="align-right-text">
                                <a class="lm__form-btn" href="@Url.ContentUrl(Model.CurrentPage.ContentLink)">
                                    @(string.IsNullOrWhiteSpace(Model.CurrentPage.ButtonConfirmText) ? "Tillbaka till listan" : Model.CurrentPage.ButtonConfirmText)
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="layout__item u-1/1 u-1/3-tablet">
                @if (Model.CurrentPage.GetLevel() >= 3)
                {
                    Html.RenderAction("GetRightNav", "Navigation", new { page = Model.CurrentPage });
                }
            </div>
        </div>
    </div>
</section>
<!-- END OF MAIN CONTENT OF WEBPAGE -->

Gro/Views/AppPages/DeliveryAssurancePage/DeliveryAssuranceList.cshtml
@using System.Globalization
@using EPiServer.Editor
@using Gro.Core.ContentTypes.Utils
@model Gro.ViewModels.Pages.AppPages.DeliveryAssurance.DeliveryAssuranceListViewModel

<section class="lm__contents">
    <div class="wrapper">
        <div class="layout  layout--large">
            <div class="layout__item u-1/1 u-2/3-tablet">
                <div class="lm__block lm__mina-avtal has-separator no-margin">
                    <div class="u-1/1 lm__blue-btn-block">
                        <h1 class="lm__page-title">@Html.PropertyFor(x => x.CurrentPage.Heading)</h1>
                        <p>@Html.Raw(Model.CurrentPage.Introduction)</p>
                        @if (Model.IsShowCreateNewLink)
                        {
                            <a href="@Model.CreateNewUrl" class="lm__blue-btn">
                                +&nbsp;&nbsp;@Html.Translate("/lantBruk/leveransForsakran/createDeliveryAssuranceButton")
                            </a>
                        }
                    </div>
                </div>
                <div class="lm__block lm__mina-avtal has-separator no-margin deliveryTableContainer" id="ListOfNotConfirmed">
                    <div class="loader-wrapper" style="display: none;">
                        <div class="loader"></div>
                    </div>
                    @Html.Partial("Partial/ListOfNotConfirmed", Model)
                </div>

                <div class="lm__block lm__mina-avtal has-separator no-margin deliveryTableContainer" id="ListOfConfirmed">
                    <div class="loader-wrapper" style="display: none;">
                        <div class="loader"></div>
                    </div>
                    @Html.Partial("Partial/ListOfConfirmed", Model)
                </div>

                <div class="lm__block lm__mina-avtal has-separator no-margin deliveryTableContainer" id="ListOfDelivered">
                    @Html.Partial("Partial/ListOfDelivered", Model)
                </div>
            </div>

            <!-- Modal for change delivery assurance not available  -->
            <div class="lm__modal__wrapper hidden" id="changeNotAvailable">
                <div class="mask"></div>
                <div class="lm__wide-modal">
                    <h3 class="lm__wide-modal__title">@Model.CurrentPage.ChangeNotAvailableHeader</h3>
                    <p>@Html.PropertyFor(x=>x.CurrentPage.ChangeNotAvailable)</p>
                    <div class="lm__wide-modal__close-btn">
                        <a href=""></a>
                    </div>
                </div>
            </div>

            <!-- Modal for showing error or information after event -->
            <div class="lm__modal__wrapper hidden" id="informationDialog">
                <div class="mask"></div>
                <div class="lm__wide-modal">
                    <h3 class="lm__wide-modal__title" id="dialogTitle"></h3>
                    <p id="dialogContent"></p>
                    <div class="lm__wide-modal__close-btn">
                        <a href=""></a>
                    </div>
                </div>
            </div>

            @if (!PageEditing.PageIsInEditMode && TempData["NotLoggedIn"] != null && (bool)TempData["NotLoggedIn"])
            {
                <div class="lm__modal__wrapper" id="errorDialog">
                    <div class="mask"></div>
                    <div class="lm__wide-modal">
                        <h3 class="lm__wide-modal__title">@Html.Translate("/lantBruk/leveransForsakran/errorMessages/error")</h3>
                        <div class="author-inform-form__column author-inform-form__column-full lm__row-margin">
                            @Html.Translate("/lantBruk/leveransForsakran/errorMessages/notLoggedIn")
                        </div>
                        <div class="lm__wide-modal__close-btn">
                            <a href=""></a>
                        </div>
                    </div>
                </div>
            }


            <!-- Modal for delete delivery assurance -->
            <div id="confirmDelete" class="lm__modal__wrapper hidden">
                <div class="mask"></div>
                <div class="lm__wide-modal author-inform-form">
                    <h3 class="lm__wide-modal__title">@Model.CurrentPage.RemoveDeliveryAssuranceConfirmText</h3>
                    <div class="lm__wide-modal__close-btn">
                        <a href=""></a>
                    </div>
                    <div class="author-inform-form__input lm__wide-modal__action-btn">
                        <button id="btnNo" class="author-inform-form__btn">Nej</button>
                        <button id="btnYes" class="author-inform-form__btn">Ja</button>
                    </div>
                </div>
            </div>

            <div class="layout__item u-1/1 u-1/3-tablet">
                @if (Model.CurrentPage.GetLevel() >= 3)
                {
                    Html.RenderAction("GetRightNav", "Navigation", new { page = Model.CurrentPage });
                }
            </div>
        </div>
    </div>
</section>